Beta time zones
Bytezoid/Zoid pull request #10
Opened 2022-11-09 01:41 UTC by Mini51

2022-11-09 05:13 UTC, amelinium23 requested changes

2022-11-09 05:13 UTC, amelinium23 commented on src/commands/timezones.ts
> +          .setChoices(
Can this can be simplified?

2022-11-09 05:13 UTC, amelinium23 commented on src/db/timezones.ts
> +  return "Timezone set"
You should timezone that you set.

2022-11-09 05:18 UTC, Mini51 commented on src/commands/timezones.ts
> +          .setChoices(
Not that I am aware off.

2022-11-09 05:19 UTC, amelinium23 commented on src/db/timezones.ts
> +  const date = "Sun, 30 May 2021 14:59:15"
What purpose of this variable?

2022-11-09 05:21 UTC, Mini51 commented on src/db/timezones.ts
> +  const date = "Sun, 30 May 2021 14:59:15"
that was done by @mmvergara

I think it is needed so both users are at the same time just different time zones so it can be compared.

2022-11-09 05:22 UTC, Mini51 commented on src/db/timezones.ts
> +  const date = "Sun, 30 May 2021 14:59:15"
its used 2 time so he might have just thought to keep it in a variable

2022-11-09 05:26 UTC, amelinium23 commented on src/db/timezones.ts
> +  const date = "Sun, 30 May 2021 14:59:15"
This also can be replaced with ``
```suggestion
  const date = new Date().toUTCString()
```

2022-11-09 05:28 UTC, Mini51 commented on src/db/timezones.ts
> +  const date = "Sun, 30 May 2021 14:59:15"
I will add my bot to the discord so I can test everything since I need 2 people to test compare

2022-11-09 05:35 UTC, Mini51 commented on src/db/timezones.ts
> +  const date = "Sun, 30 May 2021 14:59:15"
Done

2022-11-09 05:36 UTC, amelinium23 commented on src/commands/timezones.ts
> +          .setChoices(
I would move it to separate file with consts.

2022-11-09 08:17 UTC, theyadev commented on src/commands/timezones.ts
> +          .setChoices(
> I would move it to separate file with consts.

I agree

2022-11-09 08:25 UTC, theyadev requested changes

2022-11-10 06:02 UTC, amelinium23 approved these changes
Looks great 👍

2022-11-13 22:23 UTC, merged